matches:
  # Discrete Math and Database Logic Symbols
  - trigger: ":not"
    replace: "¬"
  - trigger: ":and"
    replace: "∧"
  - trigger: ":or"
    replace: "∨"
  - trigger: ":xor"
    replace: "⊕"
  - trigger: ":im"
    replace: "→"
  - trigger: ":bi"
    replace: "↔"
  - trigger: ":eq"
    replace: "≡"
  - trigger: ":neq"
    replace: "≠"
  - trigger: ":all"
    replace: "∀"
  - trigger: ":fora"
    replace: "∀"
  - trigger: ":some"
    replace: "Ǝ"
  - trigger: ":theree"
    replace: "Ǝ"
  - trigger: ":ex"
    replace: "Ǝ"
  - trigger: ":sel"
    replace: "σ"
  - trigger: ":proj"
    replace: "π"
  - trigger: ":uni"
    replace: "∪"
  - trigger: ":int"
    replace: "∩"
  - trigger: ":div"
    replace: "÷"
  - trigger: ":join"
    replace: "⋈"
  - trigger: ":theref"
    replace: "∴"
